name: iw_rest_client
description: This project is an implementation that allow developers to encapsulate their own usage of a http client.
version: 1.0.5
repository: https://github.com/euivanw/iw_rest_client

topics:
  - http
  - rest

environment:
  sdk: ">=3.0.0 <4.0.0"

scripts: derry.yaml

dependencies:
  collection: ^1.18.0
  http: ^1.1.1

dev_dependencies:
  lints: ^3.0.0
  mocktail: ^1.0.1
  test: ^1.24.9
