name: iw_rest_client
description: >
  This project is an implementation that allow developers to encapsulate their own usage of a http client.
  The main objective of this project is to create a package that provide http client encapsulated and by doing this allow developers to use it in many apps rather than create their own encapsulation for each project.
  For now, the package supports only Dart http client, however, other clients could be supported in the future, por instance, the Dio http client.

version: 1.0.2
repository: https://github.com/euivanw/iw_rest_client

topics:
  - http
  - rest

environment:
  sdk: ">=3.0.0 <4.0.0"

scripts: derry.yaml

dependencies:
  collection: ^1.18.0
  http: ^1.1.0

dev_dependencies:
  lints: ^3.0.0
  mocktail: ^1.0.1
  test: ^1.24.9
